apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "renovate.fullname" . }}-config
  labels:
    {{- include "renovate.labels" . | nindent 4 }}
data:
  config.json: |-
    {{ required "A valid .Values.renovate.config entry is required!" .Values.renovate.config | nindent 4 }}
